## **Acknowledgments**

***

We would like to acknowledge [Oscar Ospina], [Brooke Fridley], and [Boyi Guo] for their expert review of this case study.

We would also like to acknowledge the National Institute of General Medical Sciences for funding this work (1R25GM160622).

Icons are from [iconpacks](https://www.iconpacks.net/).

Avatars are from [avataaars](https://getavataaars.com/).

### AI Attribution Statement


This work was primarily human-created. AI was used to make stylistic edits, such as changes to structure, wording, and clarity. AI was prompted for its contributions, or AI assistance was enabled. AI-generated content was reviewed and approved. The following model(s) or application(s) were used: Google Gemini, Microsoft 356 Copilot (GPT-5).

AIA Primarily human, Stylistic edits, Human-initiated, Reviewed, Google Gemini, Microsoft 356 Copilot (GPT-5) v1.0

More information about this AI attribution can be found [here](https://aiattribution.github.io/).


<!-- Author information -->
[Oscar Ospina]: https://www.linkedin.com/in/oscareospina/
[Brooke Fridley]: https://www.childrensmercy.org/childrens-mercy-research-institute/research-areas/labs-and-research-teams/fridley-lab/
[Boyi Guo]: https://boyi-guo.com/