# **Data Visualization**
***


If you have been following along but stopped, we could load our imported data like so:

Add instructions for loading the data...

***
<details> <summary> If you skipped the data import section click here. </summary>

Add instructions for loading the data...

</details>
***

The genes SST and FKBP5 are both annotated in the Figure 2a Volcano Plot as DEGs. SST is downregulated in SCZ cases and FKBP5 is upregulated in SCZ cases.

Therefore, we're going to make quilt plots showing the expression of these genes for each spot/cell in two samples (one NTC and one SCZ).

Note that quilt plots don't require histology image (image of the tissue), because the spatial coordinates data that we input provides x and y coordinates for the center of each cell/spot. Therefore, we can place the location of these cells without a tissue image.

Also note that this is Xenium data which means there are a lot of cells! So we're going to use the `ptsize` argument to set the point size of the spots or cells to be really small. If we make it too large, it's dense/cramped/hard to view the quilt plot

I'm using the `PRGn` color palette because I wanted one that I knew should be color vision deficiency friendly, and it reminds of viridis. However, I'm not a huge fan of the white being intermediate expression values. Feels like it's a better palette where the values are centered around some value. The `BuRd` one used in the basic functions vignette for `spatialGE` also has white in the middle. Is there another color palette that you'd recommend that doesn't have white in the middle or am I overthinking the choice of palette?

We have ggpubr combine the common legends and display them on the bottom. It also is plotting the quilt plots in a 2 X 2 grid

```{r, eval = FALSE}
quilt25 <- STplot(scz_spatial,
                  samples = samples_metadata$X1[c(2,5)],
                  genes = c("SST", "FKBP5"),
                  color_pal='PRGn',
                  ptsize=0.05)

ggpubr::ggarrange(plotlist=quilt25,
                  nrow=2,
                  ncol=2,
                  legend='bottom',
                  common.legend = TRUE)
```

Add plot here

***
